/*
 * TD Ameritrade API
 *
 * TD Ameritrade API
 *
 * API version: 3.0.1
 * Contact: austin.millan@gmail.com
 */

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	_context "context"
	_ioutil "io/ioutil"
	_nethttp "net/http"
	_neturl "net/url"
	"strings"
)

// Linger please
var (
	_ _context.Context
)

// MarketHoursApiService MarketHoursApi service
type MarketHoursApiService service

type ApiGetHoursRequest struct {
	ctx _context.Context
	ApiService *MarketHoursApiService
	apikey *string
	markets *string
	date *string
}

func (r ApiGetHoursRequest) Apikey(apikey string) ApiGetHoursRequest {
	r.apikey = &apikey
	return r
}
func (r ApiGetHoursRequest) Markets(markets string) ApiGetHoursRequest {
	r.markets = &markets
	return r
}
func (r ApiGetHoursRequest) Date(date string) ApiGetHoursRequest {
	r.date = &date
	return r
}

func (r ApiGetHoursRequest) Execute() (Hours, *_nethttp.Response, error) {
	return r.ApiService.GetHoursExecute(r)
}

/*
 * GetHours Operating hours of markets
 * Retrieve market hours for specified markets
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @return ApiGetHoursRequest
 */
func (a *MarketHoursApiService) GetHours(ctx _context.Context) ApiGetHoursRequest {
	return ApiGetHoursRequest{
		ApiService: a,
		ctx: ctx,
	}
}

/*
 * Execute executes the request
 * @return Hours
 */
func (a *MarketHoursApiService) GetHoursExecute(r ApiGetHoursRequest) (Hours, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  Hours
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "MarketHoursApiService.GetHours")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/marketdata/hours"

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}
	if r.apikey == nil {
		return localVarReturnValue, nil, reportError("apikey is required and must be specified")
	}
	if r.markets == nil {
		return localVarReturnValue, nil, reportError("markets is required and must be specified")
	}
	if r.date == nil {
		return localVarReturnValue, nil, reportError("date is required and must be specified")
	}

	localVarQueryParams.Add("apikey", parameterToString(*r.apikey, ""))
	localVarQueryParams.Add("markets", parameterToString(*r.markets, ""))
	localVarQueryParams.Add("date", parameterToString(*r.date, ""))
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Bearer"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}

type ApiGetMarketHoursRequest struct {
	ctx _context.Context
	ApiService *MarketHoursApiService
	apikey *string
	market string
	date *string
}

func (r ApiGetMarketHoursRequest) Apikey(apikey string) ApiGetMarketHoursRequest {
	r.apikey = &apikey
	return r
}
func (r ApiGetMarketHoursRequest) Date(date string) ApiGetMarketHoursRequest {
	r.date = &date
	return r
}

func (r ApiGetMarketHoursRequest) Execute() (Hours, *_nethttp.Response, error) {
	return r.ApiService.GetMarketHoursExecute(r)
}

/*
 * GetMarketHours Operating hours of markets
 * Retrieve market hours for specified single market
 * @param ctx _context.Context - for authentication, logging, cancellation, deadlines, tracing, etc. Passed from http.Request or context.Background().
 * @param market The markets for which you're requesting market hours, comma-separated. Valid markets are EQUITY, OPTION, FUTURE, BOND, or FOREX.
 * @return ApiGetMarketHoursRequest
 */
func (a *MarketHoursApiService) GetMarketHours(ctx _context.Context, market string) ApiGetMarketHoursRequest {
	return ApiGetMarketHoursRequest{
		ApiService: a,
		ctx: ctx,
		market: market,
	}
}

/*
 * Execute executes the request
 * @return Hours
 */
func (a *MarketHoursApiService) GetMarketHoursExecute(r ApiGetMarketHoursRequest) (Hours, *_nethttp.Response, error) {
	var (
		localVarHTTPMethod   = _nethttp.MethodGet
		localVarPostBody     interface{}
		localVarFormFileName string
		localVarFileName     string
		localVarFileBytes    []byte
		localVarReturnValue  Hours
	)

	localBasePath, err := a.client.cfg.ServerURLWithContext(r.ctx, "MarketHoursApiService.GetMarketHours")
	if err != nil {
		return localVarReturnValue, nil, GenericOpenAPIError{error: err.Error()}
	}

	localVarPath := localBasePath + "/marketdata/{market}/hours"
	localVarPath = strings.Replace(localVarPath, "{"+"market"+"}", _neturl.PathEscape(parameterToString(r.market, "")), -1)

	localVarHeaderParams := make(map[string]string)
	localVarQueryParams := _neturl.Values{}
	localVarFormParams := _neturl.Values{}
	if r.apikey == nil {
		return localVarReturnValue, nil, reportError("apikey is required and must be specified")
	}
	if r.date == nil {
		return localVarReturnValue, nil, reportError("date is required and must be specified")
	}

	localVarQueryParams.Add("apikey", parameterToString(*r.apikey, ""))
	localVarQueryParams.Add("date", parameterToString(*r.date, ""))
	// to determine the Content-Type header
	localVarHTTPContentTypes := []string{}

	// set Content-Type header
	localVarHTTPContentType := selectHeaderContentType(localVarHTTPContentTypes)
	if localVarHTTPContentType != "" {
		localVarHeaderParams["Content-Type"] = localVarHTTPContentType
	}

	// to determine the Accept header
	localVarHTTPHeaderAccepts := []string{"application/json"}

	// set Accept header
	localVarHTTPHeaderAccept := selectHeaderAccept(localVarHTTPHeaderAccepts)
	if localVarHTTPHeaderAccept != "" {
		localVarHeaderParams["Accept"] = localVarHTTPHeaderAccept
	}
	if r.ctx != nil {
		// API Key Authentication
		if auth, ok := r.ctx.Value(ContextAPIKeys).(map[string]APIKey); ok {
			if apiKey, ok := auth["Bearer"]; ok {
				var key string
				if apiKey.Prefix != "" {
					key = apiKey.Prefix + " " + apiKey.Key
				} else {
					key = apiKey.Key
				}
				localVarHeaderParams["Authorization"] = key
			}
		}
	}
	req, err := a.client.prepareRequest(r.ctx, localVarPath, localVarHTTPMethod, localVarPostBody, localVarHeaderParams, localVarQueryParams, localVarFormParams, localVarFormFileName, localVarFileName, localVarFileBytes)
	if err != nil {
		return localVarReturnValue, nil, err
	}

	localVarHTTPResponse, err := a.client.callAPI(req)
	if err != nil || localVarHTTPResponse == nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	localVarBody, err := _ioutil.ReadAll(localVarHTTPResponse.Body)
	localVarHTTPResponse.Body.Close()
	localVarHTTPResponse.Body = _ioutil.NopCloser(bytes.NewBuffer(localVarBody))
	if err != nil {
		return localVarReturnValue, localVarHTTPResponse, err
	}

	if localVarHTTPResponse.StatusCode >= 300 {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: localVarHTTPResponse.Status,
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	err = a.client.decode(&localVarReturnValue, localVarBody, localVarHTTPResponse.Header.Get("Content-Type"))
	if err != nil {
		newErr := GenericOpenAPIError{
			body:  localVarBody,
			error: err.Error(),
		}
		return localVarReturnValue, localVarHTTPResponse, newErr
	}

	return localVarReturnValue, localVarHTTPResponse, nil
}
